#!/usr/bin/env python

#import subprocess
import rospy
import roslaunch
import subprocess
import time

class open_launch():
	def __init__(self):
		rospy.init_node("launch_node", anonymous=True)
		#rospy.on_shutdown(open_launch.shutdown())
		uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)
		roslaunch.configure_logging(uuid)
		bringup_launch = roslaunch.parent.ROSLaunchParent(uuid,["/home/pi/catkin_ws/src/turtlebot3/turtlebot3_bringup/launch/turtlebot3_robot.launch"])
		bringup_launch.start()
	#def shutdown(self):
	#	rospy.loginfo("shutdown launch")
	#	launch.shutdown()

	def main(self):
		rospy.spin()

if __name__ == "__main__":
	node = open_launch()
	node.main()
	




'''
cmd = ["roslaunch", "turtlebot3_bringup", "turtlebot3_robot.launch"]
proc = subprocess.Popen(cmd)

time.sleep(5)
#proc.terminate()
'''
