#! /usr/bin/env python
# _*_ coding:utf-8 _*_

import rospy
import numpy as np
from geometry_msgs.msg import Twist
from sensor_msgs.msg import LaserScan
import time
from std_msgs.msg import UInt8

class tunnel():
	def __init__(self):
		self.pub_cmd_vel = rospy.Publisher("cmd_vel", Twist, queue_size=10)
		while not rospy.is_shutdown():			
			self.go_straight()

	def go_straight(self):
			print("go_tunnel")
			twist = Twist()
			twist.linear.x = 0.21
			twist.angular.z = 0.0
			self.pub_cmd_vel.publish(twist)



	def main(self):
		rospy.spin()





	
if __name__ == "__main__":
	rospy.init_node('tunnel_1')
	node = tunnel()
	node.main()
