#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
from geometry_msgs.msg import Twist
from turtlebot3_autorace_msgs.msg import MovingParam

class ControlMoving():
	def __init__(self):
		self.pub_cmd_vel = rospy.Publisher('/cmd_vel', Twist, queue_size = 1)
	
	
	def straight(self): 
		twist = Twist()
		twist.linear.x = 0.1
		twist.linear.y = 0
		twist.linear.z = 0
		twist.angular.x = 0
		twist.angular.y = 0
		twist.angular.z = 0 #-30

		self.pub_cmd_vel.publish(twist)

	def main(self):
		while not rospy.is_shutdown():
			rospy.loginfo("straight to 0.1")
			self.straight()
        	

if __name__ == '__main__':
	rospy.init_node('Control_moving', anonymous=False)
	ControlMoving().main()
